### ISSUE TITLE
Reverse the order of version values in the tooltip 

### ISSUE THREAD

**Issue by sweetpea22** [ChainSafe/nodewatch-ui#46]
UX nit, if we sort the versions by latest->oldest might be easier viewing. If we reverse it, it'll correspond with the bar's colors. Let me know if there's issues with this! 😃
<img width="632" alt="Screen Shot 2021-09-10 at 11 00 43 AM" src="https://user-images.githubusercontent.com/47398578/132883279-dcd7a6af-2fc4-43d1-9856-d1b80fd7a036.png">

**Comment by tanmoyAtb** [comment]
Hey, I tries the reverse technique, reversing the bars reverses the tooltip as well !
I would need to create custom tooltips to make this work !!!
